#!/bin/bash
# AWS EUM Manual Installation Commands

echo "=== AWS EUM Manual Installation ==="
echo ""
echo "1. Direct Docker Installation:"
echo "docker run -d \\"
echo "  --name aws-eum \\"
echo "  -p 80:80 \\"
echo "  -e AWS_ACCESS_KEY_ID=your_key_here \\"
echo "  -e AWS_SECRET_ACCESS_KEY=your_secret_here \\"
echo "  -e AWS_REGION=eu-west-2 \\"
echo "  -v /mnt/user/appdata/aws-eum:/app/data \\"
echo "  ghcr.io/n85uk/aws-eum:latest"
echo ""
echo "2. Docker Compose (create docker-compose.yml first):"
echo "version: '3.8'"
echo "services:"
echo "  aws-eum:"
echo "    image: ghcr.io/n85uk/aws-eum:latest"
echo "    container_name: aws-eum"
echo "    restart: unless-stopped"
echo "    ports:"
echo "      - \"80:80\""
echo "    environment:"
echo "      - AWS_ACCESS_KEY_ID=your_key_here"
echo "      - AWS_SECRET_ACCESS_KEY=your_secret_here"
echo "      - AWS_REGION=eu-west-2"
echo "    volumes:"
echo "      - ./data:/app/data"
echo "    networks:"
echo "      - br0.100"
echo ""
echo "networks:"
echo "  br0.100:"
echo "    external: true"
echo ""
echo "3. UNraid Docker Template (Manual):"
echo "In UNraid web UI:"
echo "- Go to Docker tab"
echo "- Click 'Add Container'"
echo "- Set Repository: ghcr.io/n85uk/aws-eum:latest"
echo "- Add environment variables as shown above"
echo "- Add volume mapping: /mnt/user/appdata/aws-eum:/app/data"
echo "- Set network to your preferred network"
