version: '3.8'

services:
  aws-2way-sms:
    build: .
    container_name: aws-2way-sms
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PORT=3000
      - NODE_ENV=production
      - DISABLE_CSP=true
    volumes:
      - ./data:/data
    networks:
      - aws-2way-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1));"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  aws-2way-network:
    driver: bridge
