name: Build and publish AWS EUM MariaDB

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/AWS_EUM_MariaDB/**'
      - '.github/workflows/build-and-publish-mariadb.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/n85uk/aws-eum-mariadb
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=enterprise,enable=true
            type=raw,value=mariadb,enable=true
            type=raw,value=2.1.2,enable=true
            type=raw,value=2.1,enable=true
            type=raw,value=2,enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Apps/AWS_EUM_MariaDB
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Update template configuration
        run: |
          echo "✅ AWS EUM MariaDB Enterprise edition Docker image built and published successfully"
          echo "📦 Tags: ${{ steps.meta.outputs.tags }}"