name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate-aws-eum-v3:
    name: Validate AWS EUM v3
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'Apps/AWS_EUM_v3/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd Apps/AWS_EUM_v3
          npm ci

      - name: Syntax check
        run: |
          cd Apps/AWS_EUM_v3
          node -c server.js
          echo "✅ Syntax check passed"

      - name: Validate package.json
        run: |
          cd Apps/AWS_EUM_v3
          npm run test || echo "No tests defined"

      - name: Check version consistency
        run: |
          cd Apps/AWS_EUM_v3
          
          PKG_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          SERVER_VERSION=$(grep "const APP_VERSION" server.js | awk -F"'" '{print $2}')
          DOCKERFILE_VERSION=$(grep 'version=' Dockerfile | awk -F'"' '{print $2}')
          
          echo "package.json version: $PKG_VERSION"
          echo "server.js version: $SERVER_VERSION"
          echo "Dockerfile version: $DOCKERFILE_VERSION"
          
          if [ "$PKG_VERSION" != "$SERVER_VERSION" ]; then
            echo "❌ Version mismatch between package.json and server.js"
            exit 1
          fi
          
          if [ "$PKG_VERSION" != "$DOCKERFILE_VERSION" ]; then
            echo "❌ Version mismatch between package.json and Dockerfile"
            exit 1
          fi
          
          echo "✅ All versions are consistent: $PKG_VERSION"

      - name: Verify required files
        run: |
          cd Apps/AWS_EUM_v3
          
          FILES=(
            "server.js"
            "package.json"
            "Dockerfile"
            "docker-compose.yml"
            "views/index-v3.ejs"
            "public/css/style-v3.css"
            "public/js/app-v3.js"
          )
          
          for file in "${FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
            echo "✅ Found: $file"
          done

      - name: Docker build test
        run: |
          cd Apps/AWS_EUM_v3
          docker build -t aws-eum-v3:test .
          echo "✅ Docker build successful"

      - name: Add PR comment
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All checks passed! Ready to merge.'
            })
