name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate-aws-eum:
    name: Validate AWS EUM
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'Apps/AWS_EUM/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (prefer lockfile; fall back when lock missing dependency)
        run: |
          cd Apps/AWS_EUM
          # If package-lock.json already includes better-sqlite3 then use npm ci for reproducible installs.
          if [ -f package-lock.json ] && grep -q '"better-sqlite3"' package-lock.json; then
            npm ci
          else
            npm install
          fi

      - name: Syntax check
        run: |
          cd Apps/AWS_EUM
          node -c server.js
          echo "✅ Syntax check passed"

      - name: Validate package.json
        run: |
          cd Apps/AWS_EUM
          npm run test || echo "No tests defined"

      - name: Check version consistency
        run: |
          cd Apps/AWS_EUM
          
          PKG_VERSION=$(cat package.json | grep '"version"' | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          SERVER_VERSION=$(grep "const APP_VERSION" server.js | awk -F"'" '{print $2}')
          DOCKERFILE_VERSION=$(grep 'version=' Dockerfile | awk -F'"' '{print $2}')
          
          echo "package.json version: $PKG_VERSION"
          echo "server.js version: $SERVER_VERSION"
          echo "Dockerfile version: $DOCKERFILE_VERSION"
          
          if [ "$PKG_VERSION" != "$SERVER_VERSION" ]; then
            echo "❌ Version mismatch between package.json and server.js"
            exit 1
          fi
          
          if [ "$PKG_VERSION" != "$DOCKERFILE_VERSION" ]; then
            echo "❌ Version mismatch between package.json and Dockerfile"
            exit 1
          fi
          
          echo "✅ All versions are consistent: $PKG_VERSION"

      - name: Verify expected files (warn if missing)
        run: |
          cd Apps/AWS_EUM
          
          FILES=(
            "server.js"
            "package.json"
            "Dockerfile"
            "docker-compose.yml"
            "views/index-v3.ejs"
            "public/css/style-v3.css"
            "public/js/app-v3.js"
          )
          
          MISSING=0
          for file in "${FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "⚠️ Missing (optional/expected): $file"
              MISSING=1
            else
              echo "✅ Found: $file"
            fi
          done
          if [ "$MISSING" -eq 1 ]; then
            echo "⚠️ Some expected files were not present; this is a warning to help maintainers review the PR."
          fi

      - name: Docker build test
        run: |
          cd Apps/AWS_EUM
          docker build -t aws-eum-v3:test .
          echo "✅ Docker build successful"

      - name: Add PR comment
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All checks passed! Ready to merge.'
            })
