name: UCG Max Webhook - CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/UCG-Max-Webhook-Receiver/**'
      - '.github/workflows/ucg-webhook-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/UCG-Max-Webhook-Receiver/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Apps/UCG-Max-Webhook-Receiver/backend
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_ucgmax
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx
    
    - name: Run tests
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_ucgmax
        SECRET_KEY: test-secret-key-for-ci
        HMAC_SECRET: test-hmac-secret
        BEARER_TOKEN: test-bearer-token
        ADMIN_USER: admin
        ADMIN_PASSWORD: test-admin-password
      run: |
        pytest tests/ -v

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Build frontend
      working-directory: Apps/UCG-Max-Webhook-Receiver/frontend
      run: |
        npm install
        npm run build
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/ucg-max-webhook-receiver
        tags: |
          type=raw,value=latest
          type=sha,prefix={{branch}}-
    
    - name: Build and push Docker image (standard)
      uses: docker/build-push-action@v5
      with:
        context: Apps/UCG-Max-Webhook-Receiver
        file: Apps/UCG-Max-Webhook-Receiver/docker/Dockerfile.backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Extract metadata (all-in-one)
      id: meta-allinone
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/ucg-max-webhook-receiver
        tags: |
          type=raw,value=allinone-latest
          type=sha,prefix=allinone-{{branch}}-
    
    - name: Build and push Docker image (all-in-one)
      uses: docker/build-push-action@v5
      with:
        context: Apps/UCG-Max-Webhook-Receiver
        file: Apps/UCG-Max-Webhook-Receiver/docker/Dockerfile.allinone
        push: true
        tags: ${{ steps.meta-allinone.outputs.tags }}
        labels: ${{ steps.meta-allinone.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
